In [0]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)

In [0]:
iris=load_iris()

In [3]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [0]:
data=pd.DataFrame(iris.data,columns=iris.feature_names)

In [5]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
#without using the Lambda Function
data['species(flower_name)']=pd.Categorical.from_codes(iris.target,iris.target_names)
data.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species(flower_name)
0                5.1               3.5  ...               0.2                setosa
1                4.9               3.0  ...               0.2                setosa
2                4.7               3.2  ...               0.2                setosa
3                4.6               3.1  ...               0.2                setosa
4                5.0               3.6  ...               0.2                setosa

[5 rows x 5 columns]

**Train,Test Dataset in a different manner **

In [0]:
data['is_train']=np.random.uniform(0,1,len(data)) <=.75

In [8]:
data.head()

sepal length (cm)  sepal width (cm)  ...  species(flower_name)  is_train
0                5.1               3.5  ...                setosa      True
1                4.9               3.0  ...                setosa      True
2                4.7               3.2  ...                setosa      True
3                4.6               3.1  ...                setosa      True
4                5.0               3.6  ...                setosa      True

[5 rows x 6 columns]

In [0]:
train,test=data[data['is_train']==True],data[data['is_train']==False]

In [10]:
print("Number of observations in Training :",len(train))
print("Number of observations in Testing :",len(test))

Number of observations in Training : 118
Number of observations in Testing : 32


In [0]:
model=RandomForestClassifier()

In [12]:
train.head()

sepal length (cm)  sepal width (cm)  ...  species(flower_name)  is_train
0                5.1               3.5  ...                setosa      True
1                4.9               3.0  ...                setosa      True
2                4.7               3.2  ...                setosa      True
3                4.6               3.1  ...                setosa      True
4                5.0               3.6  ...                setosa      True

[5 rows x 6 columns]

In [13]:
test.head()

sepal length (cm)  sepal width (cm)  ...  species(flower_name)  is_train
7                 5.0               3.4  ...                setosa     False
8                 4.4               2.9  ...                setosa     False
10                5.4               3.7  ...                setosa     False
13                4.3               3.0  ...                setosa     False
17                5.1               3.5  ...                setosa     False

[5 rows x 6 columns]

In [14]:
features= data.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [0]:
model=RandomForestClassifier()


In [18]:
y_target=pd.factorize(train['species(flower_name)'])[0]
y_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
model.fit(train[features],y_target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [21]:
model.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
model.predict_proba(test[features])[0:10]

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [0]:
name_pre=iris.target_names[model.predict(test[features])]

In [24]:
name_pre

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [28]:
#CONFUSION MATRIX IN ANOTHER FORMAT

pd.crosstab(test['species(flower_name)'],name_pre,rownames=['Actual Species'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [0]:
#MODEL ACCURACY = (30/32)*100 