In [0]:
import pandas as pd
import numpy as np

In [0]:
from sklearn import datasets
iris=datasets.load_iris()

In [0]:
X=iris.data
y=iris.target

**Using K Nearest Neighbors**


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [0]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [9]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [10]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [11]:
knn.predict([[3,4,5,2]])

array([1])

In [13]:
knn.predict(X_test)

array([2, 0, 1, 1, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 2,
       2, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 1, 2, 0, 2, 1, 0, 1, 2, 2,
       0])

In [14]:
y_test

array([2, 0, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 2, 0, 2, 1, 2, 0, 0, 2, 2,
       2, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 1, 2, 0, 2, 1, 0, 1, 2, 2,
       0])

In [0]:
c=knn.predict(X_test)

In [21]:
knn.score(X_test,y_test)

0.9555555555555556

In [0]:
a=knn.predict([[3,4,5,5]])

In [23]:
a

array([2])

In [26]:
print("Name of the Category : ",iris['target_names'][a])

Name of the Category :  ['virginica']


In [27]:
for i in knn.predict(X_test):
  print("Predicted Name of the Category : ",iris['target_names'][i])

Predicted Name of the Category :  virginica
Predicted Name of the Category :  setosa
Predicted Name of the Category :  versicolor
Predicted Name of the Category :  versicolor
Predicted Name of the Category :  setosa
Predicted Name of the Category :  virginica
Predicted Name of the Category :  versicolor
Predicted Name of the Category :  setosa
Predicted Name of the Category :  versicolor
Predicted Name of the Category :  versicolor
Predicted Name of the Category :  virginica
Predicted Name of the Category :  virginica
Predicted Name of the Category :  setosa
Predicted Name of the Category :  virginica
Predicted Name of the Category :  setosa
Predicted Name of the Category :  virginica
Predicted Name of the Category :  versicolor
Predicted Name of the Category :  virginica
Predicted Name of the Category :  setosa
Predicted Name of the Category :  setosa
Predicted Name of the Category :  virginica
Predicted Name of the Category :  virginica
Predicted Name of the Category :  virginica
Pre

**Using Logistics Regression**

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
lr=LogisticRegression()

In [30]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
lr.predict(X_test)

array([2, 0, 1, 1, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 2,
       2, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 1, 2, 0, 2, 1, 0, 1, 2, 2,
       0])

In [32]:
lr.score(X_test,y_test)

0.9555555555555556