In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

In [0]:
digits=load_digits()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [35]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Logistic Regression**

In [36]:
model_lr=LogisticRegression()
model_lr.fit(x_train,y_train)
model_lr.score(x_test,y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9685185185185186

# **Support Vector Machine**

In [37]:
model_svm=SVC()
# If i provide gamma parameter in the SVC() parameter then the score will be 32
model_svm.fit(x_train,y_train)
model_svm.score(x_test,y_test)

0.9962962962962963

# **Random Forest Classifier**

In [38]:
model_rf=RandomForestClassifier(n_estimators=80)
model_rf.fit(x_train,y_train)
model_rf.score(x_test,y_test)

0.9814814814814815

In [39]:
model_rf=RandomForestClassifier()
model_rf.fit(x_train,y_train)
model_rf.score(x_test,y_test)

0.9777777777777777

# **K Fold Validation**

In [40]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [41]:
for train_index ,test_index in kf.split([1,2,3,4,5,6,7,8,9,10,11,21]):
  print(train_index,test_index)

[ 3  4  5  6  7  8  9 10 11] [0 1 2]
[ 0  1  2  6  7  8  9 10 11] [3 4 5]
[ 0  1  2  3  4  5  9 10 11] [6 7 8]
[0 1 2 3 4 5 6 7 8] [ 9 10 11]


# **KFOLD for the Digits dataset**

In [0]:
#Stratified KFLOD has to be used due to remove Overlappping

In [0]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [0]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [0]:
scores_lr=[]
scores_svm=[]
scores_rf=[]

In [0]:
for train_index,test_index in folds.split(digits.data,digits.target):
  x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
  scores_lr.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),x_train,x_test,y_train,y_test))
  scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

In [47]:
scores_lr


[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [48]:
scores_rf

[0.9449081803005008, 0.9532554257095158, 0.9232053422370617]

In [49]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

# **Cross_Validation**

In [51]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=4)

array([0.93777778, 0.91091314, 0.95768374, 0.90423163])

In [53]:
cross_val_score(SVC(),digits.data,digits.target,cv=4)

array([0.96222222, 0.96659243, 0.98218263, 0.95100223])

In [54]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=4)

array([0.93333333, 0.90868597, 0.96659243, 0.92873051])